### ISSUE TITLE
Buttons shifted slightly to the left on mobile

### ISSUE THREAD

**Issue by devChuk** [Hack-The-City/hack-the-city.github.io#8]
Note how the questions & sponsor buttons are shifted slightly to the left

![](https://fbcdn-photos-e-a.akamaihd.net/hphotos-ak-xtf1/v/t34.0-0/p206x206/12231359_933733623373752_131995021_n.jpg?oh=da3a8b3681dc951ed6ea09061f799e7a&oe=5644C9CC&__gda__=1447357719_c190877831f5b942de2e68c1096ff4cd)

**Comment by nicolaifsf** [comment]
Take a looksie.
